### PR TITLE
Prevent failure when no hex files in download_path

### PR DESCRIPTION
**Pull request by Geekfish**
Some times I would clean up my downloads folder and upyflashed would grumpily fail. This will keep it running and log instead.

### CODE REVIEW

**Comment by tomviner** [comment]
Thanks Eleni!

**Comment by tomviner** [comment]
@Geekfish you may want to install the latest from master/pypi as I found the short circuit loop left my lap(top) getting a bit hot! So I refactored the loop to ensure the sleep always happens.

**Comment by Geekfish** [comment]
Oops :see_no_evil: !! Thanks @tomviner !

**Comment by Geekfish** [comment]
Actually I'm having some trouble installing the latest version from pypi:

``` bash
$ pip install -U upyflashed --no-cache-dir
Collecting upyflashed
  Downloading upyflashed-1.1.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/ll/_r6fwzs12mbg115frb4rlk6r0000gn/T/pip-build-LpzGDE/upyflashed/setup.py", line 15, in <module>
        long_description=read('README.rst') + read('CHANGES.rst'),
      File "/private/var/folders/ll/_r6fwzs12mbg115frb4rlk6r0000gn/T/pip-build-LpzGDE/upyflashed/setup.py", line 6, in read
        return open(os.path.join(os.path.dirname(__file__), fname)).read()
    IOError: [Errno 2] No such file or directory: '/private/var/folders/ll/_r6fwzs12mbg115frb4rlk6r0000gn/T/pip-build-LpzGDE/upyflashed/CHANGES.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/ll/_r6fwzs12mbg115frb4rlk6r0000gn/T/pip-build-LpzGDE/upyflashed
```

**Comment by tomviner** [comment]
@Geekfish thanks for the report! try again now

**Pull request merged**
